### 1. 첫번째 멤버 정보 조회(id=1)
GET {{host}}/api/hello?id=1

### 2. id=2 멤버 저장
POST {{host}}/api/hello
Content-Type: application/json

{
  "name" : "jungseop",
  "phone" : "01011112222",
  "age" : 28,
  "userId" : "9709",
  "password" : "pwpw"
}

### 3. 두번째 멤버 정보 조회(id=2)
GET {{host}}/api/hello?id=2

### 4. 모든 멤버 정보 조회
GET {{host}}/api/hello/list

### 5. userId=9709인 멤버(id=2) 정보 수정
PUT {{host}}/api/hello
Content-Type: application/json

{
  "name" : "jungseop2",
  "phone" : "01012341234",
  "age" : 282,
  "userId" : "9709",
  "password" : "pwpw2"
}

### 6. 수정 후 두번째 멤버 정보 조회(id=2)
GET {{host}}/api/hello?id=2

### 7. 두번째 멤버 정보 삭제
DELETE {{host}}/api/hello?id=2

### 8. 삭제 후 두번째 멤버 정보 조회(id=2)
GET {{host}}/api/hello?id=2